# Generated by Django 5.0.4 on 2024-05-14 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='logins',
        ),
    ]
